### ISSUE TITLE
Use this model on tensorflow

### ISSUE THREAD

**Issue by antoineheinentest** [julienheinen/Vegetal_ML#1]
Hello, I would like to use this model in tensorflow, in order to integrate it into a web application. Is it possible to convert it to Tensorflow?  Thanks in advance

**Comment by julienheinen** [comment]
Hello, yes it is possible to convert it to tensorflow Lite. Here's a video showing the various steps 
[How to convert your ML model to TensorFlow Lite (TensorFlow Tip of the Week)](https://www.youtube.com/watch?v=MZx1fhbL2q4)
In addition, this tensorflow org website may answer your question 
[Convertisseur TensorFlow Lite ](https://www.tensorflow.org/lite/convert?hl=fr)

If you have any further questions, please don't hesitate to contact me.
